# network
network-id="1201"

# gas
min-gas-price=0

# data
data-path="/opt/besu/data"
logging="INFO"
host-whitelist=["prometheus","172.24.2.16","localhost","127.0.0.1"]

# p2p
p2p-port="30303"
max-peers=25

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port="8545"
rpc-http-api=["DEBUG","ETH","ADMIN","WEB3","IBFT","NET"]
rpc-http-cors-origins=["127.0.0.1","localhost","prometheus","172.24.2.16"]

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="9545"


